### ISSUE TITLE
ターン途中で解禁された政治体制は即座に反映されるかどうか

### ISSUE THREAD

**Issue by 3100** [civbg/rule#10]
おそらく次ターンまで待つ必要があるのですが
どこかに明記されていたら教えて下さい。

**Comment by doragon** [comment]
http://chaos.sakuraweb.com/sc/bg/civ_sum2.pdf
こちらに「簡易ターンサマリー：開始フェイズ」でのみ、政治体制の変更が書いてあります。そのため、それ以外のフェーズでは変更できないと考えられます。

**Comment by 3100** [comment]
それ、若干古いんですよね。。（拡張とFAQ2.0が反映されてません。。）

**Comment by 3100** [comment]
~~~
However, a player only has one opportunity to change directly to
a new government. If the player wishes to change to a different
government on any turn other than the turn immediately after
unlocking that government, they must first change to the
Anarchy transitional government.
~~~
説明書 P.14

即座に変えられるけど、その場合は無政府状態になって次のターンに政治体制が変更される。つまり、結局解禁した次のターンに無政府状態なしで変更する方が良い、と。
