### ISSUE TITLE
略奪点の効果はどれが最新？

### ISSUE THREAD

**Issue by 3100** [civbg/rule#11]
FAQ2.0かと思いますので
公式ルールに沿った回答をmdファイルに記述すると良さそうですね。

**Comment by doragon** [comment]
http://vivit-jc.hatenablog.com/entry/2013/09/17/060839
上記サイトに情報がありました。Civilizationボードゲーム FAQ ver2.0 和訳ということですので、こちらが回答になるかと思います。

戦闘終了時の略奪

基本的には戦闘の敗者が損害を受けることに変わりはないのですが、ルールをわかりやすく、食い違いのないようにするために調整しました。
（訳注：以下の内容は『富と栄光』の拡張に既に含まれている）

戦闘によりフィギュアが失われたとき：勝者は略奪点1を得る
首都でない都市が攻撃され、敗北したとき：勝者は略奪点2を得る
首都が攻撃され、敗北したとき：勝者が軍事勝利を達成し、ゲームを終了する

勝者は直ちに以下の表の中から実行可能な略奪を選びます。略奪点2を得ている場合、プレイヤーは略奪2の効果を選ぶか、略奪1の効果を2回（違う効果を2つ、あるいは同じ効果を2回）選ぶことになります。

略奪1
・敗者から商業点を最大3点奪う
・敗者から文化点を最大3点奪う
・敗者から資源トークンを1つ奪う（村や小屋トークンを選ぶこともできるが、選ぶ前に表を見てはいけない）
・敗者のコイントークンを1枚選び、それを失わせる

略奪2
・敗者が取得済みで、勝者が取得していない技術を1つ直ちに得る
・敗者の文化イベントカードを1枚奪う（表を見ずに選ぶ）
・敗者のコイントークンを1枚奪う

**Comment by 3100** [comment]
:+1:

**Comment by doragon** [comment]
https://github.com/civbg/rule/pull/15

**Comment by 3100** [comment]
thx!
