### ISSUE TITLE
日本における合理主義について

### ISSUE THREAD

**Issue by doragon** [civbg/rule#13]
自分はよくわかっていないのですが、何が問題だったのでしょうか？
日本では技術研究時に3商業点減りますが、それが合理主義にも反映されるかどうかという問題ですか？

**Comment by 3100** [comment]
Japanese after a learning play | Sid Meier's Civilization: The Board Game – Wisdom and Warfare | BoardGameGeek
http://boardgamegeek.com/thread/1031809/japanese-after-learning-play

の解釈をとることが多いのかなと考えていました（以前自分がプレイしたところもこれでした）

**Comment by doragon** [comment]
了解です！そうなると、日本の合理主義はあまり強くないかもしれませんね^^;

**Comment by 3100** [comment]
ひとまずハウスルールとして運用しますね
