### ISSUE TITLE
「市民の反乱」カードはターン開始フェイズの始めに使えるか？

### ISSUE THREAD

**Issue by 3100** [civbg/rule#2]
「市民の反乱」カードがターン開始フェイズにいつでも使えるのか、それとも自分の手番まで使えないのか？

**Comment by doragon** [comment]
文化イベントカードは対応しているフェーズであればいつでも使えるというルールで良い気がします。ローカルなのかもしれませんが、その方が他のカードもわかりやすいかと…。

**Comment by 3100** [comment]
自分で聞いておいてなんですが、手番順に回すフェイズなので、割り込みが明記されていないカードの場合はダメかもしれませんね。

**Comment by doragon** [comment]
ハウスルールとして、
＞手番順に回すフェイズなので、割り込みが明記されていないカードの場合はダメ
とする方が良さそうですね。

**Comment by 3100** [comment]
他の方に異存がなければ、うちのハウスルールとして解釈したいと思います。

**Comment by doragon** [comment]
https://github.com/civbg/rule/pull/14

**Comment by 3100** [comment]
PRがマージされた後に閉じると尚良いとおもいます。thx

**Comment by doragon** [comment]
すみません、気をつけます。。。
