### ISSUE TITLE
合理主義のルールについて記述する

### ISSUE THREAD

**Issue by 3100** [civbg/rule#21]
合理主義は色々とハウスルールによって扱いが異なる技術ですが
今までのゲームでは、1ターンの間に、レベル1、2をそれぞれ1つまで開発できるという解釈をしています。
一応BGGのルールも確認しつつ、mdに明記しようと思います。

**Comment by y-takasuka** [comment]
この解釈で問題ないので、クローズで良いと思います

**Comment by 3100** [comment]
ルールをmdファイルに書かなくても、大丈夫そうですか？

**Comment by y-takasuka** [comment]
書かなくてもいいと思います、自分は最初からその解釈だったので。

**Comment by 3100** [comment]
異論がある方がいたら、再オープンしてください。

**Comment by doragon** [comment]
769e8b4e632b4fee3aa2704364c35eb56348add6
