### ISSUE TITLE
「軍事的伝統」の修正ルールについて

### ISSUE THREAD

**Issue by 3100** [civbg/rule#3]
この効力がとても強力なので、一部のハウスルールでは部隊カードと軍隊フィギュアを入れ替えて解釈するようです。僕たちのハウスルールではどうしましょうか？

**Comment by doragon** [comment]
+1

**Comment by doragon** [comment]
特に異論がなければ、こちらで確定してもよろしいでしょうか？

**Comment by doragon** [comment]
現状そこまで問題になっていないので、部隊カードと軍隊フィギュアを入れ替えることはしない。

**Comment by 3100** [comment]
一度閉じておきますね。必要になったら再オープンしましょう。
