### ISSUE TITLE
ドイツが「兵站学」を開発した際の効果

### ISSUE THREAD

**Issue by 3100** [civbg/rule#8]
ドイツの文明特性
~~~
ゲームの準備後、部隊を進歩させたり解禁したりする技術を研究するたびに、
ドイツはその部隊を1枚無料で生産し、市場から任意の資源を1つ得る。
~~~
をどう解釈するのが良いでしょう？

1. 3兵種の部隊を1枚ずつ無料で生産し、任意の資源を3つ得る。
1. 3兵種の部隊を1枚ずつ無料で生産し、任意の資源を1つ得る。
1. 3兵種のうちいずれかの部隊を1枚無料で生産し、任意の資源を1つ得る。

他のハウスルールや、解釈などが記載されたWebページなどの情報も歓迎です。

**Comment by 3100** [comment]
cf. [Germans in W&W with logistics | Sid Meier's Civilization: The Board Game – Wisdom and Warfare | BoardGameGeek](http://boardgamegeek.com/thread/1090081/germans-ww-logistics)

**Comment by y-takasuka** [comment]
個人的な感想ですが、「兵站学」は三種同時に進歩するので、
> 1.3兵種の部隊を1枚ずつ無料で生産し、任意の資源を3つ得る。
が妥当ではないかと思います。

**Comment by doragon** [comment]
ちなみに以前やったときは、3でやりましたね。

**Comment by 3100** [comment]
公式ではないですが、実質的には1.という採用が多いそうです。(boardgamegeek由来)

というわけで、`ハウスルール`として1.を検討しようかと思いますが、いかがでしょうか？

cf. [civilization board game - How many units and resources will the Germans get when they research logistics? - Board & Card Games Stack Exchange](http://boardgames.stackexchange.com/questions/23243/how-many-units-and-resources-will-the-germans-get-when-they-research-logistics)

**Comment by doragon** [comment]
+1

**Comment by y-takasuka** [comment]
依存ありません。
これでクローズでいいと思います。
